### ISSUE TITLE
Water Reuse- Additional Energy Consumption is not included in the GHG emission avoided due to electricity

### ISSUE THREAD

**Issue by harora16** [icra/ecam#100]
![ecam 1](https://user-images.githubusercontent.com/38723394/40625227-7b673832-62b1-11e8-9d39-c77579712447.png)
![ecam 2](https://user-images.githubusercontent.com/38723394/40625257-95ce6ff6-62b1-11e8-8137-de1cba2a8f2b.png)
@holalluis @Ranf16 @Porro1jc

**Comment by holalluis** [comment]
I think it should not be included. Please confirm

**Comment by Porro1jc** [comment]
It should be subtracted from the kWh saved due to reuse displacing potable water.  For example if you displace 1000 m3 of potable water through reuse and it results in a total of 1000 kWh less for abstraction, treatment, and distribution than if you were not reusing, BUT, you are spending 500 kWh additional to produce or pump the reuse water, then your net GHG avoided is 500 kWh.  Depending on the reuse treatment technology, like reverse osmosis, you could even possibly have negative values for GHG avoided, meaning you increased abstraction, treatment, and distribution emissions from the reuse.
