### ISSUE TITLE
Graphs for substages

### ISSUE THREAD

**Issue by Porro1jc** [icra/ecam#111]
@holalluis @Ranf16 @harora16

If any graphs for substages are not working, then we should hide them.  

![ecam2 1 edits](https://user-images.githubusercontent.com/20580315/40844695-a1b9b694-6582-11e8-998c-b69c67cfc906.png)

**Comment by holalluis** [comment]
ok, done

**Comment by Ranf16** [comment]
@holalluis @Ranf16 @harora16

I can still see the buttons. see screenshot below. 

I think all the graphs of substages need to be hided. Even though the one for standardized energy is ok, the problem is that is shows the same graph in all stages. I.e. if you assessed pumps in abstraction it shows the same graph in wastewater treatment. 

![image](https://user-images.githubusercontent.com/33861734/40891934-5d3a4cae-678f-11e8-8d37-c5a705a62c79.png)

**Comment by holalluis** [comment]
maybe you need to reset the caché, please try again
