### ISSUE TITLE
N content and TVS values for faecal sludge types (missing)

### ISSUE THREAD

**Issue by holalluis** [icra/ecam#129]
![captura de pantalla de 2018-08-27 12-10-40](https://user-images.githubusercontent.com/1082644/44654638-a62dcf80-a9f2-11e8-85b4-3b00ff5592dd.png)

**Comment by holalluis** [comment]
@Ranf16 will provide the numbers

**Comment by holalluis** [comment]
closed because of issue #168

**Comment by Ranf16** [comment]
Dear Lluis,

it is quite difficult to get good default values for this because faecal sludge can have very different compositions. I will provide the values by Monday but I'd like to ask you to do the following so that the user can still influence what happens:

**1.** The values for N_content and TVS should be taken from the table like it currently happens, but at the same time should the user be able to see the values and adapt them. Therefore add these two as inputs:

**land application of faecal sludge**
- Total Nitrogen [% of dry weight] <- this is N_content; 
- Add a estimate button that assigns the value from the table to the input

**landfilling of faecal sludge**
- Total volatile solids [% of dry weight] <- this is TVS
- Add a estimate button that assigns the value from the table to the input

**2.** Change the order of the inputs
- The Selection of the type of faecal sludge should be first
- Then the dry weight
- then the new inputs mentioned above.


![image](https://user-images.githubusercontent.com/33861734/46815713-bf5cc680-cd7b-11e8-8b50-a5f939f9e79a.png)

**Comment by Ranf16** [comment]
Here are the default values for the estimations:



Type | Total N [% of dry   weight] | TVS [% of dry   weight] | TS [%]
-- | -- | -- | --
Untreated faecal sludge | 0.24% | 70.00% | 4.00%
Treated faecal sludge (Typical) | 3% | 40% | 22.00%
Pit hummus | 4% | 65% | 7.00%
Dried faeces | 3.00% | 70.00% | 27.00%
Composted faecal sludge | 3% | 80.00% | 8.00%
Septic  tank sludge | 0.03% | 60.00% | 2.00%

Please note also the previous comment, regarding renaming and making those values available as inputs. 

Please see the image below to avoid confusion regarding what value in the table belongs to what in the Tool. 

![image](https://user-images.githubusercontent.com/33861734/47286237-1c634280-d5ee-11e8-867e-07b10a048ea4.png)

**Comment by Ranf16** [comment]
thanks. You can close this issue. I can't close it
