### ISSUE TITLE
FST stage: duplicated drop down menu

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#139]
Is it possible that the two drop down menus are linked, so that we can replace the second one? I am asking because the user should always select the same treatment type in both, so having to make the same selection two times will feel redundant to the user. 

![image](https://user-images.githubusercontent.com/33861734/45029774-0acbd880-b04a-11e8-82e9-64cdab94dec7.png)

If it is not possible to remove  the second drop down menu, then please rename it to 

"Main process from which sludge is removed"
Long description: Type of treatment process from whichf excess sludge is removed"

**Comment by holalluis** [comment]
There is a problem here: the equation for the estimation for the BOD removed as sludge ("fst_bod_sludge") needs a treatment type to be selected, that's why it appears. And also, we still need the user to be able to change the emission factor ("fst_ch4_efac") manually, that's why we need the dropdown menu twice... Another solution would be add this dropdown menu below the "BOD removed as sludge", but we would still have the same dropdown menu twice...

**Comment by Ranf16** [comment]
Please let's discuss this. 

If it is not avoidable to have a second dropdown menu,I would change the appearance.

Actually what the user selects with the menu is the rate of BOD removed as excess sludge, so in that case I would name it also that way and show the value (similar to the case of emission factor):

![image](https://user-images.githubusercontent.com/33861734/45080327-f42e8b80-b0f4-11e8-86ff-c4b8dd74ba7b.png)

**Comment by holalluis** [comment]
Solved, now we see the percentage of the influent BOD removed, and the absolute value as well in parentheses:
![captura de pantalla 2018-09-05 a las 18 03 38](https://user-images.githubusercontent.com/1082644/45106079-0c72ca80-b136-11e8-9412-ac22aacc66fa.png)
