### ISSUE TITLE
Add info in the attachement to "Summary of estimations at this level"

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#208]
The attachement contains all the estimations of FSM, they should be added to the summary of estimations page. 

[Estimations (003).docx](https://github.com/icra/ecam/files/2525674/Estimations.003.docx)

**Comment by Ranf16** [comment]
By the way: this is not urgent. This can be done after launching V.2.2

**Comment by holalluis** [comment]
Hi Ranjin, I think that instead of having all the estimations written in the web we could have a PDF document that summarizes all of them with a link in the web, that would make it a lot easier for me, because writing all this document in HTML code is very time consuming. Can you discuss this wit GIZ? thanks

**Comment by holalluis** [comment]
The problem of having this document in parallel is that is disconnected from the tool, and if we keep improving/modifying it, this document will have to be updated as well, which is not ideal, since it can accumulate errors or things not updated over time. I have a better idea: I can code a page with an estimation renderer from the equations that form the estimations, then, if we add more estimations, they will be displayed automatically

**Comment by TobiasGIZ** [comment]
OK, go ahead as suggested.
