### ISSUE TITLE
Decimal points

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#251]
(For ECAM 3.0) Dear Lluis, is it possible to automatically remove the decimal points when copying numbers from an Excel sheet to the ECAM tool?
For example: Copying 1,000,000 from an excel sheet and paste this into ECAM result in 1 and not one million. 

If the "Read Excel Sheet" function works in the future, this shouldn't be a problem anymore, right?

Video with example can be found [here](https://www.dropbox.com/s/vdsr9zkg0td017l/Issue_decimal_point.mp4?dl=0).

Best, Elaine

**Comment by holalluis** [comment]
Hi Elaine, this is a kind of complex issue, since there can be multiple cases, since there are several number formatting styles depending on the country of the user. The tool must receive inputs without number formatting, for example, "1,234,567.89" should be introduced as "1234567.89", since this is the standard way of dealing with numbers for all programming languages (at least that I'm aware of)
