### ISSUE TITLE
Opportunities Page, change biogas % to m³

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#252]
(For ECAM 3.0) Dear Lluis, it would be better, if "Biogas production" would be followed by m³ instead of % and "MUST ENTER in cubic meters".
![Biogas Production, change unit to m³](https://user-images.githubusercontent.com/45791540/80358186-4d27d600-887c-11ea-8f6d-0804e2f194bd.png)

Further, instead of "Desired percent change" it should only say "Desired change"
![Opportunities Page, unit](https://user-images.githubusercontent.com/45791540/80358176-49944f00-887c-11ea-9152-b7689ae658bd.png)

Thanks, Elaine

**Comment by holalluis** [comment]
Dear Elaine, 

Ok I will change it for v3. I did not code this page, it was a patch done during my holidays, done by another developer, and that's why it looks unfinished and not 100% in line with the rest of the tool. We can discuss how it should exactly work for v3, since I'm redoing all the user interface from scratch, and also I never clearly understood how this opportunities part should work.

Regards,
Lluís

**Comment by holalluis** [comment]
I close this issue, since opportunities page is removed in v3 for now, if in the future we have a good idea on how to do it, and a clear definition on its functionality we can discuss it to redo the opportunities page from scratch.
