### ISSUE TITLE
FSM Population (restructuring)

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#260]
Hi Lluis, regarding population:

The "resident population" of FSM can remain in the FSM "main stage":
![image](https://user-images.githubusercontent.com/45791540/89166039-b99c2a80-d579-11ea-8904-f321544a9fd1.png)

However, "Population with onsite Treatment" should be 1) Renamed to "Population with On-Site Containment Systems" and 2) moved to the Stage "Containment"

Further. another kind of population should be added above "Population with On-Site Containment Systems". There should be a possibility to include "Population with Open Defaecation". 

**Currently**, the user has to include the people with no form of treatment under "population with onsite treatment" , which is misleading. In the containment stage, the user has to select "open defaecation" (see screenshot).
![image](https://user-images.githubusercontent.com/45791540/89168009-78f1e080-d57c-11ea-9d42-515e58f0387c.png)

This is misleading and should be separated. After adding "Population with Open Defaecation" and "Population with On-Site Treatment Systems", the should be a matrix added with all kinds of containment systems, where you can include the percentage of population with e.g. 40 % pit latrines , 5% septic tanks etc (see exmaple in screenshot).
![image](https://user-images.githubusercontent.com/45791540/89168263-e43bb280-d57c-11ea-8b8e-7a115b824a01.png)

**Comment by holalluis** [comment]
Dear Elaine, it is not clear to me where I should add this SFD matrix. Also, to rename a variable, I cannot do in only one language, I should receive the translation for each language, otherwise we'll have misleading translations in other languages. This is also the case for new variables like the new proposed variable. For the moment, it is ok for me to move the variable "fs_onsi_pop" to Containment.

**Comment by holalluis** [comment]
now all populations are in the new stage "Wastewater Transport"
