### ISSUE TITLE
Emissions Factor (uncollected wastewater)

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#284]
Dear @holalluis ,

I've noticed that in ECAM 2.2 it says CH4 emission factor (uncollected wastewater) see screen shot:
![image](https://user-images.githubusercontent.com/45791540/104908129-4b5fee80-5986-11eb-8b88-ab95d895b392.png)

While in ECAM 3.0 it says CH4 emission factor (collected wastewater).
![image](https://user-images.githubusercontent.com/45791540/104908222-6e8a9e00-5986-11eb-8d3c-1446d3858b12.png)

Is there a reason?

**Comment by holalluis** [comment]
discuss uncollected wastewater concept next meeting @lcorominas @ElaChe00

**Comment by holalluis** [comment]
They are different emission factors: the first (from v2.2) was for uncollected water, and the one from v3 is for collected water. They have the same default number (0.3 kgCH4/kgBOD), because both refer to untreated water.
![image](https://user-images.githubusercontent.com/1082644/107824497-dd8ac500-6d81-11eb-80d5-9079b42a037a.png)
