### ISSUE TITLE
Graphics "serviced population" | adapt colour for consistancy

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#287]
Hey @holalluis ,

could you please adapt the colours of the graphics for serviced population? Currently, both are blue- but it would make sense to have the same colour as for "water supply" and for "sanitation":

Currently:
![image](https://user-images.githubusercontent.com/45791540/105022903-904d5900-5a4a-11eb-90fd-473c67bd72f9.png)

Better would be those colours:
![image](https://user-images.githubusercontent.com/45791540/105022929-9d6a4800-5a4a-11eb-954b-7da51b476596.png)

The colour code for blue is: #56C2DB
The colour code for red is: #EC6D57

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/108765379-fb131800-7553-11eb-9fd1-99e42e7e966a.png)
Hi @ElaChe00, I've opted to draw this info in pie charts, since I had to adapt the whole functionality of bar charts to draw different colors just for this, so in order to keep the code simple I did it with the pie charts, is this ok for you?

**Comment by ElaChe00** [comment]
Yes, this is fine! No need to make it more completed than it needs to be!

Remove "Distribution" and "Treatment or onsite sanitation".

So it only shows "Serviced population" and "Resident population"

It's clear to what it refers.

**Comment by holalluis** [comment]
ok, done, please check

**Comment by ElaChe00** [comment]
Great thx
