### ISSUE TITLE
Please change "File" to "Click here to load existing file"

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#342]
Please change "File" to "Click here to load existing file"

![image](https://user-images.githubusercontent.com/45791540/116042414-aa608e00-a66e-11eb-812d-d50f5ea4eb7b.png)

Hola Lluis, I know we had the discussion before, but several colleagues mentioned that "File" is not clear enough. Since I agree with them, it would be great to adapt the name.

I know where you are coming from and if this were a programme like Word, PPT  etc. it would be clear. But since this is ECAM 3.0, straight forward titles would suit better

**Comment by holalluis** [comment]
Dear Elaine, I agree that the text can be more descriptive, but it should also include that you can save the file from this menu. I fear that the little description may get too long for this purpose, since I think that "Click here to load or save a file" could be a tooltip that appears if you mouse over the keyword "File"

**Comment by holalluis** [comment]
![image](https://user-images.githubusercontent.com/1082644/116286388-76c95500-a78f-11eb-8bc4-fd71787d8468.png)

I think that something like this works, what do you think?

**Comment by ElaChe00** [comment]
Definitely better! I'd like to check with the colleagues too what they think. Because it is unlikely that someone will hover over the file button.
