### ISSUE TITLE
FAQ | How can I get involved?

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#417]
This question should be the last question of "**ECAM-related questions"**

**How can I get involved?**

ECAM is a free and open source tool. The source code is openly published for use and modification on github. If you want to get involved to improve the handling of ECAM or to adapt the tool to your needs, please do so on GitHub.

[Click here to access ECAM on GitHub](https://github.com/icra/ecam)

There are different ways to navigate through github:
- "**Issues**": Create and use issues to track ideas, enhancements, tasks, or bugs. Issues are a way to collect user feedback or to start discussion on certain subjects
- "**Pull requests**": Pull requests let you tell others about changes you have pushed to a banch in a repository on GitHub. Once a pull request is opened, you can discuss and review the potential changes with collaborators and add follow-up commits before your changes are merged into the base branch.

**Comment by holalluis** [comment]
done please check

**Comment by ElaChe00** [comment]
It is possible to work with Bullet Points?

![image](https://user-images.githubusercontent.com/45791540/122075151-215a0d80-cdfa-11eb-84eb-f45059e65591.png)

**Comment by holalluis** [comment]
yes, please check now

**Comment by ElaChe00** [comment]
But also Bold? 

Maybe we can remove the "s

**Comment by holalluis** [comment]
yes. It's not ideal because we are adding HTML inside, then it's difficult to translate as a whole piece of text, but as long as it is not a very specific format, it's doable.
![image](https://user-images.githubusercontent.com/1082644/122077445-09838900-cdfc-11eb-90ad-97d02be3b519.png)
 
![image](https://user-images.githubusercontent.com/1082644/122077379-fb356d00-cdfb-11eb-867a-b54698575e25.png)

**Comment by ElaChe00** [comment]
I understand. But it does look better now :D
