### ISSUE TITLE
Tip: Configuration Page "Replace"

### ISSUE THREAD

**Issue by ElaChe00** [icra/ecam#432]
@holalluis :
![image](https://user-images.githubusercontent.com/45791540/122218444-be767e00-ceae-11eb-8365-e5f72e12fdb1.png)

Please change to:
![image](https://user-images.githubusercontent.com/45791540/122219316-9cc9c680-ceaf-11eb-8977-e9bccd65fb1d.png)

Is it feasible?

**Comment by holalluis** [comment]
yes, also I've changed a little bit the look of the tips to make them look as "post-its", because I think that if you are not familiar with the tool, it's not easy to distinguish a tip from the rest of the menus of ecam, now I think it's clear without even reading the content of the tip
![image](https://user-images.githubusercontent.com/1082644/122258122-fc849980-ced0-11eb-9fad-9189166dbf65.png)

**Comment by ElaChe00** [comment]
Nice! I like it very much! I will continue to post more tips the next days.
