### ISSUE TITLE
Value for BOD effluent load in WW treatment keeps disappearing

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#457]
@ElaChe00 
When I first open a file that I prepared yesterday the results are shown, even though for some reason the BOD effluent value has disappeared. For some substages it is still possible to enter the value again, for others it isn't. When I click on those treatment substages the input field is not there any more and the results have disappeared. Output says "missing inputs"

Browser caché has been deleted.

See video that shows the bug:
https://www.dropbox.com/s/8zxayzf9r0fc4u8/ECAM3%20bug.mp4?dl=0

Here is the json file that I used: https://www.dropbox.com/s/3ft6vg0zf1jvuh9/WWTP%20Adlia%2C%20Batumi%202040%2BWWTP%20Adlia%2C%20Batumi%20%28Baseline%29.json?dl=0

**Comment by Ranf16** [comment]
Some more details. I found out that the value disappears in case the value was manually entered instead of using the estimate function. When I use the estimate function the value does not disappear.

**Comment by holalluis** [comment]
I'm looking for the cause of this

**Comment by holalluis** [comment]
This bug is being to find so far, I could reproduce the bug withoug loading a file, so the problem is not in the json file loading, the issue happens when two different substages have the same exact numeric value for wwt_bod_infl and this value is not 0, I think I'm close to find the problem

**Comment by holalluis** [comment]
I've found the problem and solved it, I've added a text for "custom value" in the places where suggestions are used
![image](https://user-images.githubusercontent.com/1082644/123848300-dcfd6000-d917-11eb-9fd3-d0415714cc3c.png)
This avoids having the dropdown menu in a "undefined" state when none of the options are selected, that state triggered the function that sets the value to the value "undefined" when the substage changed.... quite obscure thing, I read in the documentation for the library that renders the user interface that is recommended to have an initial value for the dropdown menus, and since here we can have any value because it is an open numeric field, I've set the "custom value" field to the same numeric value of the substage
