### ISSUE TITLE
delete wxx_std_elec_eff

### ISSUE THREAD

**Issue by holalluis** [icra/ecam#66]
wst_KPI_std_elec_eff is also in:

```
wst_KPI_std_elec_eff:function(){return 100*0.2725/this.wst_KPI_std_nrg_cons()},
wwc_KPI_std_elec_eff:function(){return 100*0.2725/this.wwc_KPI_std_nrg_cons()},
wwt_KPI_std_elec_eff:function(){return 100*0.2725/this.wwt_KPI_std_nrg_cons()},
```

**Comment by Porro1jc** [comment]
revise formula as indicated in the instructions.

**Comment by Ranf16** [comment]
@Porro1jc and @holalluis : The revision of formulas stated in the instructions is not for the outputs Lluis is asking for. 

The *KPI_std_elec_eff are for the _estimated efficiency of **current** pump_. We discussed to remove them because they can not be calculated with the given inputs (i.e. the value does not change with pump size, type etc.) . Instead we have the _Electromechanical efficiency of existing pump_ which is a more valuable indicator in this case. 

So therefore, we should remove all three. Thanks for noticing this Lluis.

**Comment by holalluis** [comment]
done
