### ISSUE TITLE
Upate GHG summary 

### ISSUE THREAD

**Issue by Ranf16** [icra/ecam#71]
Please see the video: https://www.dropbox.com/s/zpwjmp92riujjf1/GHG%20summary.mp4?dl=0

Summary of the video:

1. Please rearange the table so that it looks like below:
![image](https://user-images.githubusercontent.com/33861734/40232297-77ab2ebc-5a9e-11e8-9078-5bfcb6e428bc.png)

2. If the substages of a stage are activated, the value of GHG emissions from the substages should be also used to calculate the total of the system and the overal total. 

3. Remove the _"(from untreated wastewater...)"_ and integrate those emissions in the collection stage again. To do so you'll need to have _resident population_ also as an input at stage and substage level. 

In addition (not in the video):

4. The unit "Kg CO2 eq" should be renamed to "Kg CO2 eq / **assessment period**"
![image](https://user-images.githubusercontent.com/33861734/40232665-0094668e-5aa0-11e8-90a0-ec110fb51841.png)

**Comment by holalluis** [comment]
Hi Ranjin, thank you for the video, it is very helpful.

I agree on the proposed change for number 1, indeed it is a better design.

For number 2, I'm not sure, because which number should you get when you have mixed options (i.e. some stages with checkbox active and some without)

For number 3 is not as easy to fix, because the untreated wastewater cannot be calculated at substage level, because you need "collected population" minus "serviced population", and serviced population is something characteristic of ww treatment, it is difficult to think about it as a characteristic of collection, unless we come up with a way of connecting collection substages with treatment substages. In this case, we can take the serviced population from the treatment substages connected to the collection substage.

I agree on number 4.

Thanks,
