### ISSUE TITLE
GHG Summary - GHG avoided table 

### ISSUE THREAD

**Issue by Porro1jc** [icra/ecam#98]
@holalluis @Ranf16 @harora16 

Revise GHG emissions avoided descriptions:
![image](https://user-images.githubusercontent.com/20580315/40622367-33eaaae4-626f-11e8-88dc-3f55b0e889b5.png)

 
Description should be as following (do not change them):
due to biogas production/valorisation 
due to water reuse displacing potable water use
due to water reuse eliminating discharge to receiving waters
due to nutrient recovery displacing synthetic fertilizer use 
due to carbon sequestration from biosolids management
Total GHG emissions avoided 

add this note for underneath GHG outside of utility boundary table:
![image](https://user-images.githubusercontent.com/20580315/40627186-795238b0-628b-11e8-9637-7fc792ca4670.png)

add this note for underneath GHG avoided table:
![image](https://user-images.githubusercontent.com/20580315/40627206-9aaeca6e-628b-11e8-81a7-964de671b4b4.png)

**Comment by holalluis** [comment]
wwt_SL_GHG_avoided
wwd_wr_GHG_avo_d
wwd_SL_ghg_non
wwd_wr_fer_avo
wwd_wr_C_seq_slu

**Comment by holalluis** [comment]
I've added the outputs in this table but I didn't modify the descriptions, because I added the same descriptions as in the substages table. We cannot have different descriptions at each page, we should have the exact same description for both, so please, knowing this, do you still want to modify the descriptions?
![captura de pantalla 2018-05-29 a las 0 47 30](https://user-images.githubusercontent.com/1082644/40631142-e5411e58-62d9-11e8-8357-dfd133ec2150.png)

**Comment by Porro1jc** [comment]
Yes I made sure the descriptions are consistent. For example because here we only show total of nutrient recovery and not nitrogen and phosphorus individually we cannot have the same description.

Sent from my iPhone

On May 28, 2018, at 6:51 PM, Lluís Bosch <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #98<https://github.com/icra/ecam/issues/98>.

**Comment by holalluis** [comment]
ok. done

**Comment by Porro1jc** [comment]
Note at the bottom of GHG avoided table should say the emissions have not been "**subtracted**" instead of not "added"

**Comment by holalluis** [comment]
ok, corrected
